version: "3.8"

services:

  app:
    image: spring-security:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - search
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database'
      - 'SPRING_DATASOURCE_USERNAME=user'
      - 'SPRING_DATASOURCE_PASSWORD=password'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'

  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
      - 'PGPORT=5432'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

  search:
    image: elasticsearch:8.12.2
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "10"
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - "9200:9200"
      - "9600:9600"

